package com.example.commerceapp.domain.model.Product

data class ProductDetail(
    val id: String? = null,
    val attributes: List<Attribute>? = null,
    val averageReviewScore: Double? = null,
    val isBest: Boolean? = null,
    val brand: Brand? = null,
    val contentText: String? = null,
    val images: List<Image>? = null,
    val isNewItem: Boolean? = null, // 신? = null,
    val menus: List<String>? = null,
    val discountPrice: Int? = null,
    val discountRate: Int? = null,
    val modelNumber: String? = null,
    val name: String? = null,
    val category: Category? = null,
    val npay: Boolean? = null,
    val nvMid: Long? = null,
    val productNo: String? = null,
    val salePrice: Int? = null,
    val soldout: Boolean? = null,
    val standardColors: List<Any>? = null,
    val standardSizes: List<Any>? = null,
    val tags: List<Tag>? = null,
    val totalReviewCount: Int? = null,
    val totalSaleCount: Int? = null,
    val unionCategories: List<Any>? = null,
)